services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vocational_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    container_name: vocational_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vocationaltraningdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  vite:
    image: node:20-alpine
    container_name: vocational_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: npm run dev -- --host

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: vocational_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db-data: